First draft at adding cookbook to monofony docs
Monofony/Docs pull request #15
Opened 2022-11-14 13:13 UTC by lbaey-mobizel

This is the sortable recipe, coming next is translatable

2022-11-14 13:24 UTC, loic425 requested changes

2022-11-14 13:24 UTC, loic425 commented on docs/cookbook.md
> +Some recipes ou might enjoy to enhance Monofony easily according to your functional needs.
```suggestion
Some recipes you might enjoy to enhance Monofony easily according to your functional needs.
```

2022-11-14 13:24 UTC, loic425 commented on docs/cookbook/sortable.md
> +We'll need doctrine extensions
```suggestion
We'll need Doctrine extensions
```

2022-11-14 13:24 UTC, loic425 commented on docs/cookbook/sortable.md
> +            'csrf_protection' => false,
hum, could we handle this?

2022-11-14 16:09 UTC, lbaey-mobizel commented on docs/cookbook/sortable.md
> +            'csrf_protection' => false,
How so ?

2022-11-18 08:06 UTC, loic425 requested changes

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/sortable.md
> +        ->setSortable(true),
```suggestion
            ->setLabel('sylius.ui.position')
            ->setPath('.')
            ->setSortable(true),
```

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/sortable.md
> +        TwigField::create('position', 'backend/book/grid/field/positionWithButtons.html.twig')
```suggestion
        TwigField::create('position', 'backend/book/grid/field/position_with_buttons.html.twig')
```
Sylius does not follow the Symfony best practices. Symfony recommands to use snake case for templates names.

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/sortable.md
> +<!-- template/backend/book/grid/field/positionWithButtons.html.twig -->
```suggestion
<!-- template/backend/book/grid/field/position_with_buttons.html.twig -->
```

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/sortable.md
> +                'label' => 'app.position',
```suggestion
                'label' => 'sylius.ui.position',
```

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/sortable.md
> +- If using ApiPlatform, update your previous tests results with the new entity sorting.
```suggestion
- If you use ApiPlatform, update your previous tests results with the new entity sorting.
```

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/translatable.md
> +          model: App\Entity\BookTranslation
```suggestion
sylius_resource:
    resources:
        app.book:
            classes:
                model: App\Entity\Book
            translation:
                classes:
                    model: App\Entity\BookTranslation
```

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/translatable.md
> +Say you want tu localize the book property `title`.
```suggestion
Let's localize the book property `title`.
```

2022-11-18 08:06 UTC, loic425 commented on docs/cookbook/translatable.md
> +And update your `Book` entity class so :
```suggestion
And update your `Book` entity class:
```

2023-01-06 15:26 UTC, merged